### ISSUE TITLE
Feature request: add an option to send messages to a single fe-user

### ISSUE THREAD

**Issue by crochelt** [Ecodev/mailing#5]
Would it be possible to add an option to send messages to a single fe-user?

**Comment by fabarea** [comment]
I don't know what is the plan for Newsletter but you could use [EXT:messenger](https://github.com/fabarea/messenger) for that - in case the feature is not in the planning for this extension which I believe. There is a BE module where you can send individual message to a FE User. Feature is in beta though.

**Comment by PowerKiKi** [comment]
I don't think there is any relation with Newsletter. Isn't ext:mailing, specifically what @crochelt asked for ?

**Comment by fabarea** [comment]
FE or BE context?
BE -> EXT:messenger
FE -> EXT:mailing which uses EXT:messenger API

Closing unless @PowerKiKi has more to add.
